//Since this project is going to be public and I didnt find it comfortable exposing my key on github (primary reason why I didnt use google places api for location suggestions)
//Therefore I decided to use a list. Ideally, should populate with an API
export const degrees = [
   "BA/BS",
   "MS",
   "Phd",
   "MBA",
   "Coding Bootcamp",
   "Junior College",
   "Certificate"
];

export const fields = [
   "Accounting",
   "Aerospace",
   "Arts",
   "Biomedical",
   "Business",
   "Computer Science",
   "Data Science",
   "Economics",
   "Fine Arts",
   "Graphic Design",
   "Management Engineering",
   "Marketing",
   "Product Design",
   "Software Engineering"
]

export const gradeScales = [
   4.0,
   5.0,
   10.0
]

//function that checks if markup generated by Rich Text editor is empty or not
export const checkDescriptionEmpty = (markup) => {
   return markup.trimEnd() === "<p></p>";
}